import { Router, Request, Response } from 'express';
import fs from 'fs';
import path from 'path';
import dotenv from 'dotenv';

const router = Router();

// Resolve .env path relative to project root (two levels up from server/src/routes/)
const ENV_PATH = path.resolve(__dirname, '../../../../.env');

interface EnvField {
  key: string;
  label: string;
  description: string;
  group: string;
  secret?: boolean;
  placeholder?: string;
  textarea?: boolean;
}

const ENV_SCHEMA: EnvField[] = [
  {
    key: 'SLACK_BOT_TOKEN',
    label: 'Slack Bot Token',
    description: 'Bot User OAuth Token from your Slack App (starts with xoxb-)',
    group: 'Slack',
    secret: true,
    placeholder: 'xoxb-...',
  },
  {
    key: 'SLACK_APP_TOKEN',
    label: 'Slack App-Level Token',
    description: 'App-level token for Socket Mode (starts with xapp-)',
    group: 'Slack',
    secret: true,
    placeholder: 'xapp-...',
  },
  {
    key: 'SLACK_SIGNING_SECRET',
    label: 'Slack Signing Secret',
    description: 'Signing secret from your Slack App credentials page',
    group: 'Slack',
    secret: true,
    placeholder: 'abc123...',
  },
  {
    key: 'ANTHROPIC_API_KEY',
    label: 'Anthropic API Key',
    description: 'API key from console.anthropic.com for AI-powered parsing and digest generation',
    group: 'AI',
    secret: true,
    placeholder: 'sk-ant-...',
  },
  {
    key: 'OWNER_SLACK_ID',
    label: 'Your Slack User ID',
    description: 'Your personal Slack member ID (e.g. U0AK57H9PT5). When set, only messages that @mention you will generate tasks during batch polling. Links are unaffected.',
    group: 'AI',
    placeholder: 'U0AK57H9PT5',
  },
  {
    key: 'CUSTOM_CONTEXT',
    label: 'Your Personal Context',
    description: 'Help the AI understand your role and priorities. Used when classifying @mentions into tasks vs. informational notes. E.g. "I\'m the lead engineer on auth and payments. Anything about prod outages or data loss is always critical."',
    group: 'AI',
    placeholder: 'e.g. I\'m the lead on Project X. My focus areas are auth, payments, and mobile performance...',
    textarea: true,
  },
  {
    key: 'PORT',
    label: 'Server Port',
    description: 'Port the backend API server listens on',
    group: 'Server',
    placeholder: '3001',
  },
  {
    key: 'P0_POLL_INTERVAL',
    label: 'P0 Poll Interval (minutes)',
    description: 'How often to poll P0 (critical) channels for new messages',
    group: 'Polling',
    placeholder: '10',
  },
  {
    key: 'P1_POLL_INTERVAL',
    label: 'P1 Poll Interval (minutes)',
    description: 'How often to poll P1 (standard) channels for new messages',
    group: 'Polling',
    placeholder: '30',
  },
  {
    key: 'HISTORY_HOURS',
    label: 'History Window (hours)',
    description: 'How many hours of message history to fetch when polling a channel',
    group: 'Polling',
    placeholder: '24',
  },
];

function readEnvFile(): Record<string, string> {
  if (!fs.existsSync(ENV_PATH)) {
    return {};
  }
  const content = fs.readFileSync(ENV_PATH, 'utf-8');
  const parsed = dotenv.parse(content);
  return parsed;
}

function writeEnvFile(values: Record<string, string>): void {
  const lines: string[] = [];

  // Group comments header
  lines.push('# Opus — Slack Channel Monitor');
  lines.push('# Auto-generated by Settings page');
  lines.push('');

  const groups: Record<string, EnvField[]> = {};
  for (const field of ENV_SCHEMA) {
    if (!groups[field.group]) groups[field.group] = [];
    groups[field.group].push(field);
  }

  for (const [group, fields] of Object.entries(groups)) {
    lines.push(`# ${group}`);
    for (const field of fields) {
      const val = values[field.key] ?? '';
      lines.push(`${field.key}=${val}`);
    }
    lines.push('');
  }

  // Preserve any extra keys not in schema
  const schemaKeys = new Set(ENV_SCHEMA.map((f) => f.key));
  const extras = Object.entries(values).filter(([k]) => !schemaKeys.has(k));
  if (extras.length > 0) {
    lines.push('# Other');
    for (const [k, v] of extras) {
      lines.push(`${k}=${v}`);
    }
  }

  fs.writeFileSync(ENV_PATH, lines.join('\n'), 'utf-8');
}

// GET /api/settings — return current env values + schema
router.get('/', (_req: Request, res: Response) => {
  try {
    const values = readEnvFile();
    // Mask secret values in response (show only if non-empty)
    const result: Record<string, string> = {};
    for (const field of ENV_SCHEMA) {
      result[field.key] = values[field.key] ?? '';
    }
    res.json({ schema: ENV_SCHEMA, values: result, envPath: ENV_PATH });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// POST /api/settings — save env values to .env file
router.post('/', (req: Request, res: Response) => {
  try {
    const incoming: Record<string, string> = req.body;

    // Merge with existing (don't wipe extra keys not in request)
    const existing = readEnvFile();
    const merged = { ...existing, ...incoming };

    writeEnvFile(merged);

    // Reload process.env so changes take effect without restart where possible
    for (const [k, v] of Object.entries(incoming)) {
      if (v !== '') {
        process.env[k] = v;
      }
    }

    res.json({ success: true, envPath: ENV_PATH });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

export default router;
